engines:
  duplication:
    enabled: false
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    checks:
      Similar code:
        enabled: false
      import/extensions:
        enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - "server/**/*.js"
exclude_paths:
- "node_modules/"
- ".nyc_output"
- "coverage"
- "server/test/"
- "UI/"