language: node_js
node_js:
  - 8.11.3

branches:
  only:
    - develop

before_script:
  - psql -c 'create database travis;' -U postgres

env:
    - SECRET_TOKEN=secretcode
    
script:
  - npm test
  
after_success: npm run coverage